apiVersion: v1
kind: ConfigMap
metadata:
  name: console-config
data:
  authorizerInstances: |
    [{"name":"authorizer","url":"{{ .Values.global.console.authorizerURL }}","apiKey":"{{ .Values.global.sidecar.rootKey }}"}]