apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aserto-console.fullname" . }}-config
  labels:
    {{- include "aserto-console.labels" . | nindent 4 }}
data:
  configurations: |
    [
      {
        "configurationType": "central_directory",
        "name": "directory",
        "directoryServiceUrl": "{{ .Values.global.console.directoryURL }}",
        "directoryApiKey": "{{ .Values.global.directory.rootKey }}",
        "directoryTenantId": "{{ .Values.global.topaz.tenantId }}"
      },
      {
        "configurationType": "auto",
        "name": "authorizer",
        "address": "{{ .Values.global.console.authorizerURL }}/api/v2/config",
        "authorizerServiceUrl": "{{ .Values.global.console.authorizerURL }}",
        "authorizerApiKey": "{{ .Values.global.topaz.rootKey }}"
      }
    ]
