---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aserto-console.fullname" . }}
  #namespace: 'aserto-console'
  labels:
    {{- include "aserto-console.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aserto-console
  template:
    metadata:
      labels:
        {{- include "aserto-console.labels" . | nindent 8 }}
    spec:
      containers:
        - name: aserto-console
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          image: ghcr.io/aserto-dev/self-hosted-console:{{ .Values.global.console.version }}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: AUTHORIZER_SERVICE_URL
              value: {{ .Values.global.console.authorizerURL }}
            - name: AUTHORIZER_API_KEY
              value: {{ .Values.global.sidecar.rootKey }}
            - name: ASERTO_DIRECTORY_URL
              value: {{ .Values.global.console.directoryURL }}
            - name: DIRECTORY_API_KEY
              value: {{ .Values.global.directory.rootKey }}
            - name: DIRECTORY_TENANT_ID
              value: {{ .Values.global.sidecar.tenantId }}
            - name: STORAGE_PATH
              value: /config
          volumeMounts:
            - mountPath: /config
              readOnly: false
              name: console-conf
      volumes:
        - name: console-conf
          configMap:
            name: console-config # place ConfigMap `nginx-conf` on /etc/nginx
            items:
              - key: authorizerInstances
                path: authorizerInstances

