---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aserto-console.fullname" . }}
  labels:
    {{- include "aserto-console.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aserto-console
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "aserto-console.labels" . | nindent 8 }}
    spec:
      containers:
        - name: aserto-console
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          image: ghcr.io/aserto-dev/self-hosted-console:{{ .Values.global.console.version }}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: STORAGE_PATH
              value: /config
            - name: CLIENT_STORAGE_PATH
              value: /storage
          volumeMounts:
            - mountPath: /config
              readOnly: false
              name: console-conf
      volumes:
        - name: console-conf
          configMap:
            name: {{ include "aserto-console.fullname" . }}-config
            items:
              - key: configurations
                path: configurations
        - name: storage
          emptyDir: {}

