---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aserto-console.fullname" . }}
  labels:
    {{- include "aserto-console.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aserto-console
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080