---
apiVersion: v1
type: opaque
kind: Secret
metadata:
  name: {{ include "aserto-directory.fullname" . }}-secret
  labels:
    {{- include "aserto-directory.labels" . | nindent 4 }}
stringData:
  initPGHOST: {{ tpl (.Values.global.postgresql.auth.postgresHost) . }}
  initPGDATABASE: {{ .Values.global.postgresql.auth.database }}
  initPGUSER: {{ .Values.global.postgresql.auth.postgresUser }}
  initPGPASSWORD: {{ .Values.global.postgresql.auth.postgresPassword }}
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: info

    api:
      grpc:
        listen_address: 0.0.0.0:8282
        connection_timeout_seconds: 2
      gateway:
        listen_address: 0.0.0.0:8383
        allowed_origins:
        - https://*.aserto.com
        - https://*aserto-console.netlify.app
        - https://*aserto.netlify.app
      health:
        listen_address: 0.0.0.0:8484
      metrics:
        listen_address: 0.0.0.0:8585
        zpages: true
        grpc:
          counters: true
          durations: true
          gateway: true

    db:
      writer:
        host: "{{ tpl (.Values.global.postgresql.auth.postgresHost) . }}"
        port: 5432
        user: {{ .Values.global.postgresql.auth.postgresUser }}
        password: {{ .Values.global.postgresql.auth.postgresPassword }}
        ssl_mode: disable
        db_name: {{ .Values.global.postgresql.auth.database }}
        debug_mode: false
        max_open_conns: 25
        max_idle_conns: 25
        conn_max_lifetime: 5
      reader:
        host: "{{ tpl (.Values.global.postgresql.auth.postgresHost) . }}"
        port: 5432
        user: tenant_reader
        password: {{ .Values.global.postgresql.auth.postgresPassword }}
        ssl_mode: disable
        db_name: {{ .Values.global.postgresql.auth.database }}
        debug_mode: false
        max_open_conns: 25
        max_idle_conns: 25
        conn_max_lifetime: 5

    directory:
      is_root_ds: false

    nats:
      enabled: false

    authorization:
      disable: true

    authentication:
      authenticators_enabled:
        root_key: true
        machine_account: false
        mtls: false
        auth0: false

      root_keys:
        {{ .Values.global.directory.rootKey }}: "root-key-directory-writer@aserto.com"

      override:
        - methods:
          - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
          authenticators_enabled:
            anonymous: true
