---
apiVersion: v1
type: opaque
kind: Secret
metadata:
  name: {{ include "aserto-directory.fullname" . }}-secret
  labels:
    {{- include "aserto-directory.labels" . | nindent 4 }}
stringData:
  initPGHOST: {{ tpl (.Values.global.postgresql.auth.postgresHost) . }}
  initPGDATABASE: {{ .Values.global.postgresql.auth.database }}
  initPGUSER: {{ .Values.global.postgresql.auth.postgresUser }}
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: info

    api:
      grpc:
        listen_address: 0.0.0.0:8282
        connection_timeout_seconds: 2
      gateway:
        listen_address: 0.0.0.0:8383
        allowed_origins:
        - https://*.aserto.com
        - https://*aserto-console.netlify.app
        - https://*aserto.netlify.app
      health:
        listen_address: 0.0.0.0:8484
      metrics:
        listen_address: 0.0.0.0:8585
        zpages: true
        grpc:
          counters: true
          durations: true
          gateway: true

    root_db:
      writer:
        host: "{{ tpl (.Values.global.postgresql.auth.postgresHost) . }}"
        port: 5432
        user: {{ .Values.global.postgresql.auth.postgresUser }}
        password: "${DIRECTORY_DB_WRITER_PASSWORD}"
        db_name: {{ .Values.global.directory.ds0.db }}
        ssl_mode: disable
        debug_mode: false
        max_open_conns: 25
        max_idle_conns: 25
        conn_max_lifetime: 5
        query_timeout_seconds: 50
      reader:
        host: "{{ tpl (.Values.global.postgresql.auth.postgresHost) . }}"
        port: 5432
        user: tenant_reader
        password: "${DIRECTORY_DB_READER_PASSWORD}"
        db_name: {{ .Values.global.directory.ds0.db }}
        ssl_mode: disable
        debug_mode: false
        max_open_conns: 25
        max_idle_conns: 25
        conn_max_lifetime: 5
    db:
      writer:
        host: "{{ tpl (.Values.global.postgresql.auth.postgresHost) . }}"
        port: 5432
        user: {{ .Values.global.postgresql.auth.postgresUser }}
        password: "${DIRECTORY_DB_WRITER_PASSWORD}"
        db_name: {{ .Values.global.directory.central.db }}
        ssl_mode: disable
        debug_mode: false
        max_open_conns: 25
        max_idle_conns: 25
        conn_max_lifetime: 5
        query_timeout_seconds: 50
      reader:
        host: "{{ tpl (.Values.global.postgresql.auth.postgresHost) . }}"
        port: 5432
        user: tenant_reader
        password: "${DIRECTORY_DB_READER_PASSWORD}"
        db_name: {{ .Values.global.directory.central.db }}
        ssl_mode: disable
        debug_mode: false
        max_open_conns: 25
        max_idle_conns: 25
        conn_max_lifetime: 5

    directory:
      root_manifest: /files/manifest.yaml
      root_ds:
        address: localhost:8282
        api_key: {{ .Values.global.directory.ds0.rootKey }}
        tenant_id: {{ .Values.global.directory.ds0.tenantID }}

    nats:
      enabled: false

    authorization:
      disable: true

    authentication:
      authenticators_enabled:
        root_key: true
        oidc: false

      root_keys:
        keys:
          {{ .Values.global.directory.central.rootKey }}: "root-key-directory-writer@aserto.com"

        tenant_overrides:
          {{ .Values.global.directory.ds0.tenantID }}:
            {{ .Values.global.directory.ds0.rootKey }}: "no-user"

      override:
        - methods:
          - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
          - /grpc.reflection.v1.ServerReflection/ServerReflectionInfo
          authenticators_enabled:
            anonymous: true
