---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aserto-directory.fullname" . }}
  labels:
    {{- include "aserto-directory.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aserto-directory
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "aserto-directory.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: ghcr-creds

      containers:
        - name: aserto-directory
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          image: ghcr.io/aserto-dev/self-hosted-directory:{{ .Values.global.directory.version }}
          args: ["--config", "/config/config.yaml", "run"]
          env:
            - name: DIRECTORY_DB_WRITER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ tpl (.Values.global.postgresql.existingSecret) . }}"
                  key: "{{ .Values.global.postgresql.secretKeys.adminPasswordKey }}"
            - name: DIRECTORY_DB_READER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ tpl (.Values.global.postgresql.existingSecret) . }}"
                  key: "{{ .Values.global.postgresql.secretKeys.adminPasswordKey }}"
          readinessProbe:
            tcpSocket:
              port: 8383
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8383
              name: https
            - containerPort: 8282
              name: https-grpc
            - containerPort: 8585
              name: http-metrics
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: files
              mountPath: "/files"
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ include "aserto-directory.fullname" . }}-secret
            items:
              - key: config.yaml
                path: config.yaml
        - name: files
          configMap:
            name: files
