apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "aserto-directory.fullname" . }}-import-sample-data
  labels:
    {{- include "aserto-directory.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 500Mi
      initContainers:
        - name: wait-for-directory
          image: golang:1.19
          command:
            - /bin/bash
            - -ex
            - -c
            - |              
              PLATFORM=`uname`
              ARCH=`uname -m`               
              if [ "$PLATFORM" == "Linux" ]; then
                 PLATFORM=linux
              elif [ "$PLATFORM" == "Darwin" ]; then
                 PLATFORM=macos
              else
                 echo "unknown platform"
                 exit 1
              fi
              
              if [ "$ARCH" == "aarch64" ]; then
                ARCH=arm64
              fi
              
              wget "https://github.com/fullstorydev/grpcurl/releases/download/v1.8.9/grpcurl_1.8.9_${PLATFORM}_${ARCH}.tar.gz" -O grpcurl.tar.gz
              tar zxf grpcurl.tar.gz
              
              while [ $(curl -ksw "%{http_code}" "https://{{ include "aserto-directory.fullname" . }}:8383/" -o /dev/null) -ne 404 ]
              do 
                sleep 5
                echo "Waiting for the service..."
              done
         
              echo ... Creating directory tenant ...
              ./grpcurl --insecure -H "authorization: basic {{ .Values.global.directory.rootKey }}" \
                -d '{"tenant": {"id": "{{ .Values.global.topaz.tenantId }}", "name": "demo"}}' \
                 {{ include "aserto-directory.fullname" . }}:8282 aserto.directory.store.v2.Store.CreateTenant
   
      containers:
        - name: import-sample-data
          image: ghcr.io/aserto-dev/topaz:{{ .Values.global.topaz.version }}
          volumeMounts:
          - mountPath: /data
            name: data
          command:
            - /bin/sh
            - -ex
            - -c
            - |
              echo ... Importing sample data ...
              
              wget https://raw.githubusercontent.com/aserto-dev/topaz/v{{ .Values.global.topaz.version }}/assets/citadel/manifest.yaml -O manifest.yaml
              wget https://raw.githubusercontent.com/aserto-dev/topaz/v{{ .Values.global.topaz.version }}/assets/citadel/citadel_objects.json -O /data/citadel_objects.json
              wget https://raw.githubusercontent.com/aserto-dev/topaz/v{{ .Values.global.topaz.version }}/assets/citadel/citadel_relations.json -O /data/citadel_relations.json
              
              ./topaz manifest set --no-check -i -H {{ include "aserto-directory.fullname" . }}:8282 -k {{ .Values.global.directory.rootKey }} --tenant-id={{ .Values.global.topaz.tenantId }} manifest.yaml
              
              ./topaz import --no-check -i -H {{ include "aserto-directory.fullname" . }}:8282 -k {{ .Values.global.directory.rootKey }} --tenant-id={{ .Values.global.topaz.tenantId }} -d /data
              
