---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aserto-directory.fullname" . }}
  labels:
    {{- include "aserto-directory.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aserto-directory
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https-api
      port: 8383
      targetPort: 8383
    - name: https-grpc
      port: 8282
      targetPort: 8282