apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "console-proxy.fullname" . }}-config
data:
  localhost.conf: |
    server {
        listen 8080;
        server_name localhost;

        location /_authorizer/ {
          proxy_pass https://{{ .Release.Name}}-aserto-authorizer:8383/;
        }

        location /_directory/ {
          proxy_pass https://{{ .Release.Name}}-aserto-directory:8383/;
        }

        location / {
          proxy_pass http://{{ .Release.Name}}-aserto-console:8080;
        }

    }