apiVersion: v1
kind: ConfigMap
metadata:
  name: localhost-conf
data:
  localhost.conf: |
    server {
        listen 8080;
        server_name localhost;

        location /_authorizer/ {
          proxy_pass https://aserto-authorizer:8383/;
        }

        location /_directory/ {
          proxy_pass https://aserto-directory:8383/;
        }

        location / {
          proxy_pass http://aserto-console:8080;
        }

    }