---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "console-proxy.fullname" . }}
  labels:
    {{- include "console-proxy.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: console-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "console-proxy.labels" . | nindent 8 }}
    spec:
      containers:
        - name: console-proxy
          image: nginx:latest
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: localhost-conf
      volumes:
        - name: localhost-conf
          configMap:
            name: {{ include "console-proxy.fullname" . }}-config
            items:
              - key: localhost.conf
                path: localhost.conf

