---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "console-proxy.fullname" . }}
  labels:
    {{- include "console-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: console-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080