---
apiVersion: v1
kind: Service
metadata:
  name: console-proxy
  #namespace:  'proxy'
  labels:
    {{- include "console-proxy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: console-proxy
  ports:
    - name: http
      port: 8080
      targetPort: 8080