---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aserto-authorizer.fullname" . }}
  labels:
    {{- include "aserto-authorizer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: aserto-authorizer
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: 8383
      targetPort: 8383
    - name: https-grpc
      port: 8282
      targetPort: 8282