---
apiVersion: v1
type: opaque
kind: Secret
metadata:
  name: directory-secret
  #namespace: 'aserto-directory'
stringData:
  config.yaml: |
    ---
    logging:
      prod: true
      log_level: info

    api:
      grpc:
        connection_timeout_seconds: 2
      gateway:
        allowed_origins:
        - https://*.aserto.com
        - https://*aserto-console.netlify.app
        - https://*aserto.netlify.app
      metrics:
        zpages: true
        grpc:
          counters: true
          durations: true
          gateway: true

    db:
        host: "{{ .Release.Name }}-postgresql"
        port: 5432
        user: postgres
        password: {{ .Values.global.postgresql.auth.postgresPassword }}
        ssl_mode: disable
        db_name: {{ .Values.global.postgresql.auth.database }}
        debug_mode: false
        max_open_conns: 25
        max_idle_conns: 25
        conn_max_lifetime: 5

    directory:
      is_root_ds: false

    nats:
      enabled: false

    authorization:
      disable: true

    authentication:
      authenticators_enabled:
        root_key: true
        machine_account: false
        mtls: false
        auth0: false

      root_keys:
        {{ .Values.global.directory.rootKey }}: "root-key-directory-writer@aserto.com"

      override:
        - methods:
          - /grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo
          authenticators_enabled:
            anonymous: true