---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aserto-directory.fullname" . }}
  #namespace: 'aserto-directory'
  labels:
    {{- include "aserto-directory.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aserto-directory
  template:
    metadata:
      labels:
        {{- include "aserto-directory.labels" . | nindent 8 }}
    spec:
      containers:
        - name: aserto-directory
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "2048Mi"
              cpu: "2000m"
          image: ghcr.io/aserto-dev/directory:{{ .Values.global.directory.version }}
          args: ["--config", "/config/config.yaml", "run"]
          readinessProbe:
            tcpSocket:
              port: 8383
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8383
              name: https
            - containerPort: 8282
              name: https-grpc
            - containerPort: 8585
              name: http-metrics
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: directory-secret
            items:
              - key: config.yaml
                path: config.yaml