apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "aserto-directory.fullname" . }}-import-sample-data
  labels:
    app.kubernetes.io/name: import-sample-data
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: import-sample-data
    spec:
      initContainers:
        - name: wait-for-directory
          image: golang:1.19
          command: [ "/bin/sh","-c" ]
          args: [ 'while [ $(curl -ksw "%{http_code}" "https://aserto-directory:8383/" -o /dev/null) -ne 404 ]; do sleep 5; echo "Waiting for the service..."; done' ]
      containers:
        - name: import-sample-data
          image: golang:1.19
          volumeMounts:
            - mountPath: /data
              name: data
          command:
            - /bin/sh
            - -c
            - |
              curl https://raw.githubusercontent.com/aserto-dev/topaz/main/assets/citadel-objects.json > /data/citadel-objects.json
              curl https://raw.githubusercontent.com/aserto-dev/topaz/main/assets/citadel-relations.json > /data/citadel-relations.json
              go install github.com/aserto-dev/topaz/cmd/topaz@latest
              topaz import --no-check -i -H aserto-directory:8282 -k {{ .Values.global.directory.rootKey }} --tenant-id={{ .Values.global.sidecar.tenantId }} -d /data
      restartPolicy: Never
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 500Mi
