# Default values for aserto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  sidecar:
    version: 0.20.11
    tenantId: 07f3e43c-a734-11ed-a7a0-002270b772a6
    policyName: policy-todo
    policyImage: ghcr.io/aserto-policies/policy-todo
    policyTag: 2
    rootKey: 997ec52a856f0911442d1fccc308a408
  directory:
    version: latest
    rootKey: c96fe48da0735cf77fdba50134f52c43
  postgresql:
    auth:
      postgresPassword: directory
      database: directory
  console:
    version: 0.0.0-20230426133900.0.gd8fc62f9
    directoryURL: http://localhost:8080/_directory
    authorizerURL: http://localhost:8080/_authorizer

replicaCount: 1

service:
  type: ClusterIP
  port: 80

