# Default values for aserto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  topaz:
    version: 0.31.3
    tenantId: 07f3e43c-a734-11ed-a7a0-002270b772a6
    policyName: policy-todo
    policyImage: ghcr.io/aserto-policies/policy-todo
    policyTag: latest
    rootKey: 997ec52a856f0911442d1fccc308a408

  directory:
    version: 0.1.0
    central:
      db: directory
      rootKey: c96fe48da0735cf77fdba50134f52c43
    ds0:
      db: ds0
      rootKey: 049aca0c880d4cc79f862d29af22c84f
      tenantID: 4574fe3e-c602-11eb-8e9a-00ce628e6e72

  postgresql:
    localServerEnabled: true
    existingSecret: "{{ .Release.Name }}-postgresql"
    secretKeys:
      adminPasswordKey: postgres-password
    auth:
      postgresHost: "{{ .Release.Name }}-postgresql"
      postgresUser: postgres
      postgresPassword: directory

  console:
    version: 0.1.7
    directoryURL: http://localhost:8080/_directory
    authorizerURL: http://localhost:8080/_authorizer

replicaCount: 1

service:
  type: ClusterIP
  port: 80

