# Default values for aserto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:

  topaz:
    version: v3-latest-test-amd64
    tenantId: 07f3e43c-a734-11ed-a7a0-002270b772a6
    policyName: policy-todo
    policyImage: ghcr.io/aserto-policies/policy-todo
    policyTag: latest
    rootKey: 997ec52a856f0911442d1fccc308a408

  directory:
    version: 0.30.4
    rootKey: c96fe48da0735cf77fdba50134f52c43

  postgresql:
    localServerEnabled: true
    existingSecret: "{{ .Release.Name }}-postgresql"
    secretKeys:
      adminPasswordKey: postgres-password
    auth:
      postgresHost: "{{ .Release.Name }}-postgresql"
      postgresUser: postgres
      postgresPassword: directory
      database: directory

  console:
    version: 0.0.0-20231101160837.0.ga9673675
    directoryURL: http://localhost:8080/_directory
    authorizerURL: http://localhost:8080/_authorizer

replicaCount: 1

service:
  type: ClusterIP
  port: 80

